from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE recepcion.pedido_ingreso_detalle
                    ADD COLUMN IF NOT EXISTS codigo_producto varchar(50),
                    ADD COLUMN IF NOT EXISTS descripcion_producto varchar(255);

                UPDATE recepcion.pedido_ingreso_detalle detalle
                SET codigo_producto = COALESCE(detalle.codigo_producto, producto.sku),
                    descripcion_producto = COALESCE(
                        detalle.descripcion_producto,
                        producto.nombre
                    )
                FROM maestros.producto producto
                WHERE producto.id_producto = detalle.id_producto
                  AND (
                    detalle.codigo_producto IS NULL
                    OR detalle.descripcion_producto IS NULL
                  );

                ALTER TABLE recepcion.pedido_ingreso_detalle
                    ALTER COLUMN codigo_producto SET NOT NULL,
                    ALTER COLUMN descripcion_producto SET NOT NULL;

                CREATE TABLE IF NOT EXISTS recepcion.incidencia (
                    id_incidencia integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    id_pedido_ingreso integer NOT NULL
                        REFERENCES recepcion.pedido_ingreso(id_pedido_ingreso)
                        ON DELETE CASCADE,
                    id_pedido_ingreso_detalle integer NOT NULL
                        REFERENCES recepcion.pedido_ingreso_detalle(
                            id_pedido_ingreso_detalle
                        ) ON DELETE CASCADE,
                    tipo varchar(50) NOT NULL,
                    descripcion text NOT NULL,
                    cantidad_afectada numeric(12, 2) NOT NULL,
                    id_usuario_responsable uuid NOT NULL
                        REFERENCES usuarios.usuario(id_usuario),
                    fecha_registro timestamptz NOT NULL,
                    CONSTRAINT chk_incidencia_cantidad
                        CHECK (cantidad_afectada > 0)
                );

                CREATE INDEX IF NOT EXISTS idx_recepcion_cliente_fecha
                    ON recepcion.pedido_ingreso(id_cliente, fecha_registro DESC);
                CREATE INDEX IF NOT EXISTS idx_recepcion_estado_fecha
                    ON recepcion.pedido_ingreso(estado, fecha_registro DESC);
                CREATE INDEX IF NOT EXISTS idx_recepcion_detalle_producto
                    ON recepcion.pedido_ingreso_detalle(id_producto);
                CREATE INDEX IF NOT EXISTS idx_incidencia_recepcion
                    ON recepcion.incidencia(id_pedido_ingreso, fecha_registro DESC);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS recepcion.idx_incidencia_recepcion;
                DROP TABLE IF EXISTS recepcion.incidencia;
                DROP INDEX IF EXISTS recepcion.idx_recepcion_detalle_producto;
                DROP INDEX IF EXISTS recepcion.idx_recepcion_estado_fecha;
                DROP INDEX IF EXISTS recepcion.idx_recepcion_cliente_fecha;
                ALTER TABLE recepcion.pedido_ingreso_detalle
                    DROP COLUMN IF EXISTS descripcion_producto,
                    DROP COLUMN IF EXISTS codigo_producto;
            """,
        )
    ]
