from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("recepciones", "0001_ep03_receiving_workflow")]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE recepcion.pedido_ingreso
                    ADD COLUMN IF NOT EXISTS transporte_brevete varchar(50);

                ALTER TABLE recepcion.pedido_ingreso_detalle
                    ADD COLUMN IF NOT EXISTS cantidad_pallets numeric(12, 2)
                        NOT NULL DEFAULT 0,
                    ADD COLUMN IF NOT EXISTS factor_conversion numeric(10, 2);

                CREATE TABLE IF NOT EXISTS recepcion.pedido_ingreso_lote (
                    id_pedido_ingreso_lote integer
                        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    id_pedido_ingreso_detalle integer NOT NULL
                        REFERENCES recepcion.pedido_ingreso_detalle(
                            id_pedido_ingreso_detalle
                        ) ON DELETE CASCADE,
                    id_lote integer NOT NULL
                        REFERENCES inventario.lote(id_lote) ON DELETE RESTRICT,
                    cantidad numeric(12, 2) NOT NULL,
                    fecha_registro timestamptz NOT NULL,
                    CONSTRAINT uq_recepcion_detalle_lote
                        UNIQUE (id_pedido_ingreso_detalle, id_lote),
                    CONSTRAINT chk_recepcion_lote_cantidad
                        CHECK (cantidad > 0)
                );

                CREATE INDEX IF NOT EXISTS idx_recepcion_lote_detalle
                    ON recepcion.pedido_ingreso_lote(
                        id_pedido_ingreso_detalle
                    );
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS recepcion.idx_recepcion_lote_detalle;
                DROP TABLE IF EXISTS recepcion.pedido_ingreso_lote;
                ALTER TABLE recepcion.pedido_ingreso_detalle
                    DROP COLUMN IF EXISTS factor_conversion,
                    DROP COLUMN IF EXISTS cantidad_pallets;
                ALTER TABLE recepcion.pedido_ingreso
                    DROP COLUMN IF EXISTS transporte_brevete;
            """,
        )
    ]
