from django.urls import path

from .views import (
    AuditEventListView,
    AuditExportView,
    BackupListCreateView,
    BackupRestoreView,
    BackupScheduleView,
    BackupValidateView,
    DeploymentRollbackView,
    DeploymentView,
    HealthCheckView,
    IntegrationExecutionView,
    IntegrationRetryView,
    PerformanceView,
    ReleaseApproveView,
    ReleaseVersionView,
    RetentionPolicyView,
    TechnicalOverviewView,
    ConditioningBillingReportView,
    ConditioningOptionsView,
    ConditioningSendBillingView,
    ConditioningServiceListView,
    ConditioningServiceReportView,
    ReboxingView,
    RepalletExecutionView,
    RepalletRequestView,
)


urlpatterns = [
    path("technical/overview/", TechnicalOverviewView.as_view(), name="technical-overview"),
    path("technical/health/check/", HealthCheckView.as_view(), name="technical-health-check"),
    path("technical/backups/", BackupListCreateView.as_view(), name="technical-backups"),
    path("technical/backups/schedule/", BackupScheduleView.as_view(), name="technical-backup-schedule"),
    path("technical/backups/<int:backup_id>/validate/", BackupValidateView.as_view(), name="technical-backup-validate"),
    path("technical/backups/<int:backup_id>/restore/", BackupRestoreView.as_view(), name="technical-backup-restore"),
    path("technical/audit/", AuditEventListView.as_view(), name="technical-audit"),
    path("technical/audit/export/", AuditExportView.as_view(), name="technical-audit-export"),
    path("technical/retention/", RetentionPolicyView.as_view(), name="technical-retention"),
    path("technical/integrations/", IntegrationExecutionView.as_view(), name="technical-integrations"),
    path("technical/integrations/<int:execution_id>/retry/", IntegrationRetryView.as_view(), name="technical-integration-retry"),
    path("technical/performance/", PerformanceView.as_view(), name="technical-performance"),
    path("technical/releases/", ReleaseVersionView.as_view(), name="technical-releases"),
    path("technical/releases/<int:version_id>/approve/", ReleaseApproveView.as_view(), name="technical-release-approve"),
    path("technical/deployments/", DeploymentView.as_view(), name="technical-deployments"),
    path("technical/deployments/<int:deployment_id>/rollback/", DeploymentRollbackView.as_view(), name="technical-deployment-rollback"),
    path("conditioning/options/", ConditioningOptionsView.as_view(), name="conditioning-options"),
    path("conditioning/services/", ConditioningServiceListView.as_view(), name="conditioning-services"),
    path("conditioning/repallet-requests/", RepalletRequestView.as_view(), name="conditioning-repallet-request"),
    path("conditioning/services/<int:service_id>/execute-repallet/", RepalletExecutionView.as_view(), name="conditioning-repallet-execution"),
    path("conditioning/reboxing/", ReboxingView.as_view(), name="conditioning-reboxing"),
    path("conditioning/services/<int:service_id>/report/", ConditioningServiceReportView.as_view(), name="conditioning-service-report"),
    path("conditioning/billing-report/", ConditioningBillingReportView.as_view(), name="conditioning-billing-report"),
    path("conditioning/services/<int:service_id>/send-billing/", ConditioningSendBillingView.as_view(), name="conditioning-send-billing"),
]
